name: 'run ci scripts'
description: 'run ci scripts'
inputs:
  script:
    description: >
      The script file to be executed, with parameters.
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ env.AWS-ROLE-TO-ASSUME }}
        aws-region: ${{ env.AWS-REGION }}
        
    - name: update file priviledge with +x
      run: |
        chmod +x ${{ env.CI-SCRIPT-WORKING-DIRECTORY }}/${{ env.CI-SCRIPT-FOLDER-NAME }}/(${{ inputs.script }} | awk -F ' ' '{ print $1 }')
      shell: bash
      
    - name: run script
      run: ${{ env.CI-SCRIPT-WORKING-DIRECTORY }}/${{ env.CI-SCRIPT-FOLDER-NAME }}/${{ inputs.script }}
      shell: bash
