name: 'run ci scripts'
description: 'run ci scripts'
inputs:
  script:
    description: >
      The script file to be executed, with parameters.
    required: true
  args:
    description: >
      arguments to be passed to the script
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ env.AWS-ROLE-TO-ASSUME }}
        role-skip-session-tagging: true
        role-duration-seconds: 1380
        aws-region: ${{ env.AWS-REGION }}  
    - name: run script
      run: ${{ env.CI-SCRIPT-WORKING-DIRECTORY }}/${{ env.CI-SCRIPT-FOLDER-NAME }}/${{ inputs.script }} ${{ inputs.args }} 
      shell: bash
